"""empty message

Revision ID: be0abeb21706
Revises: 
Create Date: 2020-09-26 13:20:26.997660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0abeb21706'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('introduction', sa.String(length=50), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('fans_count', sa.Integer(), nullable=True),
    sa.Column('profile_photo', sa.String(length=130), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_user')
    # ### end Alembic commands ###
